### ISSUE TITLE
Might find indexes on tables useful

### ISSUE THREAD

**Issue by PeterDarley** [TCP-Lab/MTP-DB#37]
Indexes go on fields in the database, and allow for faster data lookup.  Basically it sticks all the data into a b-tree (or similar structure) to do lookups and sorts, but makes insertions slightly slower.  Without this when you do a query like: select * from cats where name='bob' it has to do a loop through cats until it finds bob.  With it it can find it in many fewer steps.

If you have a table that is very large, or you have a query that joins a bunch of tables, it's generally a good idea to have indexes on the fields that are being looked up/joined.  Many people will wait for a query to get slow before starting to add indexes.

SQLite automatically adds indexes on any Primary Key fields, or Unique fields.

**Comment by MrHedmad** [comment]
Thanks for writing here. We'll definetely keep it in mind if and when speed becomes an issue. ❤️

**Comment by MrHedmad** [comment]
I've check this this afternoon and *most* useful places where indexes make sense seem to already have them (I've marked them as Primary or Unique), while in others I don't see them making much sense. Thanks!

**Comment by MrHedmad** [comment]
As soon as I say something stupid it bites me in the ass. I've just now ran into a performance issue that indexes fixed. So, thanks @PeterDarley ! (commit ba20dcf)
